/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2024-2024. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */
import { cloudDatabase } from '@kit.CloudFoundationKit';

class CloudBill extends cloudDatabase.DatabaseObject {
  public cloudId: string;
  public accountId: string;
  public userId: string;
  public bookId: string;
  public localId: number;
  public paymentAccountLocalId: number;
  public paymentAccountName: string;
  public categoryLocalId: number;
  public amount: number;
  public type: string;
  public category: string;
  public remark: string;
  public date: string;
  public createdAt: number;
  public updatedAt: number;
  public deleted: number;

  public naturalbase_ClassName(): string {
    return 'CloudBill';
  }
}

export { CloudBill };
