/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2024-2024. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */
import { cloudDatabase } from '@kit.CloudFoundationKit';

class CloudAccountBook extends cloudDatabase.DatabaseObject {
  public cloudId: string;
  public ownerUserId: string;
  public localId: number;
  public name: string;
  public currency: string;
  public createdAt: number;
  public updatedAt: number;
  public deleted: number;

  public naturalbase_ClassName(): string {
    return 'CloudAccountBook';
  }
}

export { CloudAccountBook };
