/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2024-2024. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */
import { cloudDatabase } from '@kit.CloudFoundationKit';

class CloudPeriodRule extends cloudDatabase.DatabaseObject {
  public cloudId: string;
  public userId: string;
  public bookId: string;
  public localId: number;
  public title: string;
  public amount: number;
  public type: string;
  public category: string;
  public remark: string;
  public cycle: string;
  public day: number;
  public month: number;
  public nextDate: string;
  public enabled: number;
  public createdAt: number;
  public updatedAt: number;
  public deleted: number;

  public naturalbase_ClassName(): string {
    return 'CloudPeriodRule';
  }
}

export { CloudPeriodRule };
