/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2024-2024. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */
import { cloudDatabase } from '@kit.CloudFoundationKit';

class CloudUserDataBundle extends cloudDatabase.DatabaseObject {
  public cloudId: string;
  public accountId: string;
  public bookId: string;
  public schemaVersion: number;
  public bookCount: number;
  public categoryCount: number;
  public accountCount: number;
  public budgetCount: number;
  public periodRuleCount: number;
  public bookJson: string;
  public categoryJson: string;
  public accountJson: string;
  public budgetJson: string;
  public periodRuleJson: string;
  public updatedAt: number;
  public deleted: number;

  public naturalbase_ClassName(): string {
    return 'CloudUserDataBundle';
  }
}

export { CloudUserDataBundle };
