/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2024-2024. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */
import { cloudDatabase } from '@kit.CloudFoundationKit';

class CloudBudgetRule extends cloudDatabase.DatabaseObject {
  public cloudId: string;
  public accountId: string;
  public userId: string;
  public bookId: string;
  public ruleId: string;
  public name: string;
  public periodType: string;
  public scopeType: string;
  public amount: number;
  public categoryIdsJson: string;
  public categoryNamesJson: string;
  public dateMode: string;
  public periodValue: string;
  public startDay: number;
  public endDay: number;
  public compareMode: string;
  public status: string;
  public enabled: number;
  public createdAt: number;
  public updatedAt: number;
  public deleted: number;

  public naturalbase_ClassName(): string {
    return 'CloudBudgetRule';
  }
}

export { CloudBudgetRule };
