/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2024-2024. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */
import { cloudDatabase } from '@kit.CloudFoundationKit';

class CloudCategory extends cloudDatabase.DatabaseObject {
  public cloudId: string;
  public userId: string;
  public bookId: string;
  public localId: number;
  public name: string;
  public icon: string;
  public color: string;
  public type: string;
  public sortOrder: number;
  public isDefault: number;
  public updatedAt: number;
  public deleted: number;

  public naturalbase_ClassName(): string {
    return 'CloudCategory';
  }
}

export { CloudCategory };
