/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2024-2024. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */
import { cloudDatabase } from '@kit.CloudFoundationKit';

class UserInfo extends cloudDatabase.DatabaseObject {
  public cloudId: string;
  public accountId: string;
  public localId: number;
  public username: string;
  public displayName: string;
  public passwordHash: string;
  public salt: string;
  public createdAt: number;
  public lastLoginAt: number;
  public updatedAt: number;

  public naturalbase_ClassName(): string {
    return 'UserInfo';
  }
}

export { UserInfo };
